CREATE TABLE question
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    text text  NOT NULL,
    topic text NOT NULL,
    CONSTRAINT question_pkey PRIMARY KEY (id)
);